### ISSUE TITLE
[Payment] 미구현 사항

### ISSUE THREAD

**Issue by hookor** [ColleyProjectGroup/ColleyProjectGroup2#67]
- [x] 사용자 필수정보 미입력시 Transaction 예외처리
- [x] 계좌 추가/삭제시 알림처리(modal,alert등)
- [x] 계좌 미선택 후 결제시 알림처리
- [x] 계좌 추가시 input length 유효성검사(digits)
- [x] 상세메세지 스타일 수정(padding)
- [x] 결제완료 페이지 HOME btn color/path 수정
- [x] 상품상세에서 비로그인시 로그인 화면으로 이동
- [x] 결제 성공 페이지 사용자 정보 추가

**Comment by 96uoow** [comment]
input에 값 입력/변경할 때마다 console창에 뜨는 부분도 없애야 할 것 같습니다

**Comment by 96uoow** [comment]
![구매 페이지](https://github.com/ColleyProjectGroup/ColleyProjectGroup2/assets/121873684/214c1863-8e24-4152-bd0f-a593cf8c56a5)
1) 모달 외 부분 배경색 들어갈 때 헤더가 위에 깔려 있는 부분

2) 계좌 추가 modal 스크롤해서 계좌추가 부분과 겹쳐지는 현상
