### ISSUE TITLE
[HEADER] 오류 수정

### ISSUE THREAD

**Issue by 96uoow** [ColleyProjectGroup/ColleyProjectGroup2#77]
- [x] 네비게이션 길이 및 위치 조정

- [x] 드롭다운 메뉴 상황에 따라서 작동 안되는 것 해결

- [x] link태그 안에 a태그 없애고 다른 이벤트로 페이지 이동되도록 구현

- [x] mypage내에서 드롭다운 메뉴가 선택안되는 부분 수정

- [x] mypage에서 네비게이션 호버시에 드롭다운메뉴 background 투명해지는 부분 수정

**Comment by hookor** [comment]
![image](https://github.com/ColleyProjectGroup/ColleyProjectGroup2/assets/115582699/799e1781-7c4b-46fe-abe6-2bc8b32d3bbf)
빠르게 스크롤시 내비게이션이 최상단까지 올라가버리는 것 같습니다!
