### ISSUE TITLE
[상품] 개선사항

### ISSUE THREAD

**Issue by hookor** [ColleyProjectGroup/ColleyProjectGroup2#80]
- [x] 메인페이지 상품분류 탭 클릭시 리렌더링
- [x] 상품상세로 이동시 로딩 중(스피너 추가? 혹은 스켈레톤)
- [x] 상품수량 인풋에서 직접 숫자 입력시 숫자를 제거했을 때 NaN출력
![image](https://github.com/ColleyProjectGroup/ColleyProjectGroup2/assets/115582699/4c061983-d853-4b00-9443-2f58a39449ea)
- [x] 상품 상세이미지 상단 탭 추가 (상품상세정보, 상품구매안내 등)
- [x] 카테고시 상세 카테고리명 텍스트 스타일 수정 => 카테고리명 삭제
- [ ] 상품 파일 폴더링 
- [x] 상품상세 추천 상품 스타일 깨지는 부분 수정 
- [x] 상품 new, best 뱃지 추가

**Comment by EungBug** [comment]
상품 상세 상단 경로 추가 구현 불가(구조상 어려움...)

**Comment by EungBug** [comment]
상품 폴더링은 전체적으로 수정하도록 하겠습니다.
